In [106]:
import pandas as pd
import gspread as gs
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

In [107]:
gc = gs.service_account('my-project.json')
sh = gc.open_by_url('https://docs.google.com/spreadsheets/d/1SUlcukpgxf6pfFQbj6DKQZXSlOhyBOSuBdbmQ2ZbhTM/edit#gid=327494290')
worksheet = sh.worksheet('missing_data')
dataframe = pd.DataFrame(worksheet.get_all_records())
df = pd.DataFrame(dataframe)

In [108]:
df = df.replace('', np.nan)

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15364 entries, 0 to 15363
Data columns (total 43 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Permit Number                           15364 non-null  object
 1   Permit Type                             15364 non-null  int64
 2   Permit Type Definition                  15364 non-null  object
 3   Permit Creation Date                    15364 non-null  object
 4   Block                                   15364 non-null  object
 5   Lot                                     15364 non-null  object
 6   Street Number                           15364 non-null  int64
 7   Street Number Suffix                    160 non-null    object
 8   Street Name                             15364 non-null  object
 9   Street Suffix                           15170 non-null  object
 10  Unit                                    2147 non-null   float64
 11  Unit Suffix                             179 non-null    object
 12  Description                             15339 non-null  object
 13  Current Status                          15364 non-null  object
 14  Current Status Date                     15364 non-null  object
 15  Filed Date                              15364 non-null  object
 16  Issued Date                             14729 non-null  object
 17  Completed Date                          9129 non-null   object
 18  First Construction Document Date        14725 non-null  object
 19  Structural Notification                 468 non-null    object
 20  Number of Existing Stories              12175 non-null  float64
 21  Number of Proposed Stories              11978 non-null  float64
 22  Voluntary Soft-Story Retrofit           11 non-null     object
 23  Fire Only Permit                        1421 non-null   object
 24  Permit Expiration Date                  11904 non-null  object
 25  Estimated Cost                          12477 non-null  float64
 26  Revised Cost                            15117 non-null  float64
 27  Existing Use                            12266 non-null  object
 28  Existing Units                          11447 non-null  float64
 29  Proposed Use                            12031 non-null  object
 30  Proposed Units                          11346 non-null  float64
 31  Plansets                                12509 non-null  float64
 32  TIDF Compliance                         0 non-null      float64
 33  Existing Construction Type              12124 non-null  float64
 34  Existing Construction Type Description  12124 non-null  object
 35  Proposed Construction Type              11947 non-null  float64
 36  Proposed Construction Type Description  11947 non-null  object
 37  Site Permit                             296 non-null    object
 38  Supervisor District                     15245 non-null  float64
 39  Neighborhoods - Analysis Boundaries     15245 non-null  object
 40  Zipcode                                 15245 non-null  float64
 41  Location                                15246 non-null  object
 42  Record ID                               15364 non-null  float64
dtypes: float64(14), int64(2), object(27)
memory usage: 5.0+ MB

In [110]:
df.drop(columns = ['TIDF Compliance', 'Voluntary Soft-Story Retrofit'], inplace = True)

In [111]:
df['Site Permit'] = df['Site Permit'].fillna(df['Site Permit'].mode()[0])

In [112]:
df['Structural Notification'] = df['Structural Notification'].fillna(df['Structural Notification'].mode()[0])

In [113]:
df['Number of Existing Stories'] = df['Number of Existing Stories'].fillna(df['Number of Existing Stories'].mean()).round()

In [114]:
df['Number of Proposed Stories'] = df['Number of Proposed Stories'].fillna(df['Number of Proposed Stories'].mean()).round()

In [115]:
df['Fire Only Permit'] = df['Fire Only Permit'].fillna(df['Fire Only Permit'].mode()[0])

In [116]:
df['Street Suffix'] = df['Street Suffix'].fillna(df['Street Suffix'].mode()[0])

In [117]:
df.drop(columns = ['Unit', 'Unit Suffix'], inplace = True)

In [118]:
df['Estimated Cost'] = df['Estimated Cost'].fillna(df['Estimated Cost'].mean()).round()
df['Estimated Cost'] = df['Estimated Cost'].replace(1, df['Estimated Cost'].mean().round())

In [119]:
df['Revised Cost'] = df['Revised Cost'].fillna(df['Revised Cost'].mean()).round()

In [120]:
# df['Revised Cost'] = df['Revised Cost'].replace(2, df['Revised Cost'].mean().round())

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15364 entries, 0 to 15363
Data columns (total 39 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Permit Number                           15364 non-null  object
 1   Permit Type                             15364 non-null  int64
 2   Permit Type Definition                  15364 non-null  object
 3   Permit Creation Date                    15364 non-null  object
 4   Block                                   15364 non-null  object
 5   Lot                                     15364 non-null  object
 6   Street Number                           15364 non-null  int64
 7   Street Number Suffix                    160 non-null    object
 8   Street Name                             15364 non-null  object
 9   Street Suffix                           15364 non-null  object
 10  Description                             15339 non-null  object
 11  Current Status                          15364 non-null  object
 12  Current Status Date                     15364 non-null  object
 13  Filed Date                              15364 non-null  object
 14  Issued Date                             14729 non-null  object
 15  Completed Date                          9129 non-null   object
 16  First Construction Document Date        14725 non-null  object
 17  Structural Notification                 15364 non-null  object
 18  Number of Existing Stories              15364 non-null  float64
 19  Number of Proposed Stories              15364 non-null  float64
 20  Fire Only Permit                        15364 non-null  object
 21  Permit Expiration Date                  11904 non-null  object
 22  Estimated Cost                          15364 non-null  float64
 23  Revised Cost                            15364 non-null  float64
 24  Existing Use                            12266 non-null  object
 25  Existing Units                          11447 non-null  float64
 26  Proposed Use                            12031 non-null  object
 27  Proposed Units                          11346 non-null  float64
 28  Plansets                                12509 non-null  float64
 29  Existing Construction Type              12124 non-null  float64
 30  Existing Construction Type Description  12124 non-null  object
 31  Proposed Construction Type              11947 non-null  float64
 32  Proposed Construction Type Description  11947 non-null  object
 33  Site Permit                             15364 non-null  object
 34  Supervisor District                     15245 non-null  float64
 35  Neighborhoods - Analysis Boundaries     15245 non-null  object
 36  Zipcode                                 15245 non-null  float64
 37  Location                                15246 non-null  object
 38  Record ID                               15364 non-null  float64
dtypes: float64(12), int64(2), object(25)
memory usage: 4.6+ MB

In [122]:
df.drop(columns='Street Number Suffix', inplace= True)

In [123]:
df['Issued Date'] = pd.to_datetime(df['Issued Date'])

df['First Construction Document Date'] = pd.to_datetime(df['First Construction Document Date'])

df['Completed Date'] =pd.to_datetime(df['Completed Date'])

df['Filed Date'] = pd.to_datetime(df['Filed Date'])

df['Current Status Date'] = pd.to_datetime(df['Current Status Date'])

df['Permit Creation Date'] = pd.to_datetime(df['Permit Creation Date'])

df['Permit Expiration Date'] = pd.to_datetime(df['Permit Expiration Date'])

In [124]:
df[['Latitude', 'Longitude']] = df['Location'].str.split(',', 2, expand=True)

/var/folders/by/7zf7bnfn5x31kvfd7xxnlz5c0000gn/T/ipykernel_955/2766484650.py:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df[['Latitude', 'Longitude']] = df['Location'].str.split(',', 2, expand=True)

In [125]:
df['Latitude'] = df['Latitude'].str.replace('(', '')

/var/folders/by/7zf7bnfn5x31kvfd7xxnlz5c0000gn/T/ipykernel_955/461807323.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Latitude'] = df['Latitude'].str.replace('(', '')

In [126]:
df['Longitude'] = df['Longitude'].str.replace(')', '')

/var/folders/by/7zf7bnfn5x31kvfd7xxnlz5c0000gn/T/ipykernel_955/1713533740.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Longitude'] = df['Longitude'].str.replace(')', '')

In [127]:
df.drop(columns='Location', inplace = True)

In [128]:
df

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Street Suffix,Description,...,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Record ID,Latitude,Longitude
0,201505000000.0,4,sign - erect,2015-05-06,326,23,140,Ellis,St,"ground fl facade: to erect illuminated, electr...",...,constr type 3,NaN,NaN,Y,3.0,Tenderloin,94102.0,1.380610e+12,37.785719256680785,-122.40852313194863
1,201604000000.0,4,sign - erect,2016-04-19,306,7,440,Geary,St,remove (e) awning and associated signs.,...,constr type 3,NaN,NaN,Y,3.0,Tenderloin,94102.0,1.420160e+12,37.78733980600732,-122.41063199757738
2,201605000000.0,3,additions alterations or repairs,2016-05-27,595,203,1647,Pacific,Av,installation of separating wall,...,constr type 1,1.0,constr type 1,Y,3.0,Russian Hill,94109.0,1.424860e+12,37.7946573324287,-122.42232562979227
3,201611000000.0,8,otc alterations permit,2016-11-07,156,11,1230,Pacific,Av,repair dryrot & stucco at front of bldg.,...,wood frame (5),5.0,wood frame (5),Y,3.0,Nob Hill,94109.0,1.443570e+12,37.79595867909168,-122.41557405519474
4,201611000000.0,6,demolitions,2016-11-28,342,1,950,Market,St,demolish retail/office/commercial 3-story buil...,...,constr type 3,NaN,NaN,Y,6.0,Tenderloin,94102.0,1.445480e+11,37.78315261897309,-122.40950883997789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15359,201306000000.0,8,otc alterations permit,2013-06-11,7104,018B,162,Farallones,St,"install finishing plumbing, finish electrical,...",...,wood frame (5),5.0,wood frame (5),Y,11.0,Oceanview/Merced/Ingleside,94112.0,1.307690e+12,37.7143177382725,-122.45793648914099
15360,201306000000.0,8,otc alterations permit,2013-06-11,3609,81,3549,20th,St,revision to 201208288466 to add a toilet in th...,...,wood frame (5),5.0,wood frame (5),Y,9.0,Mission,94110.0,1.307690e+12,37.7583635958755,-122.42012861020109
15361,201306000000.0,8,otc alterations permit,2013-06-11,3609,81,3551,20th,St,revision to 201208288466 to add a toilet in th...,...,wood frame (5),5.0,wood frame (5),Y,9.0,Mission,94110.0,1.307690e+12,37.7583635958755,-122.42012861020109
15362,201306000000.0,8,otc alterations permit,2013-06-11,4260,13,2334,25th,St,"interior renovation unit #2334, new kitchen fi...",...,wood frame (5),5.0,wood frame (5),Y,10.0,Potrero Hill,94107.0,1.307690e+12,37.752135529825054,-122.40206132582264
15363,M400947,8,otc alterations permit,2013-06-11,3701,53,66,08th,St,street space permit,...,NaN,NaN,NaN,Y,6.0,South of Market,94103.0,1.307690e+12,37.777338241377954,-122.41391079039403

In [129]:
df.dtypes

Permit Number                                     object
Permit Type                                        int64
Permit Type Definition                            object
Permit Creation Date                      datetime64[ns]
Block                                             object
Lot                                               object
Street Number                                      int64
Street Name                                       object
Street Suffix                                     object
Description                                       object
Current Status                                    object
Current Status Date                       datetime64[ns]
Filed Date                                datetime64[ns]
Issued Date                               datetime64[ns]
Completed Date                            datetime64[ns]
First Construction Document Date          datetime64[ns]
Structural Notification                           object
Number of Existing Stories                       float64
Number of Proposed Stories                       float64
Fire Only Permit                                  object
Permit Expiration Date                    datetime64[ns]
Estimated Cost                                   float64
Revised Cost                                     float64
Existing Use                                      object
Existing Units                                   float64
Proposed Use                                      object
Proposed Units                                   float64
Plansets                                         float64
Existing Construction Type                       float64
Existing Construction Type Description            object
Proposed Construction Type                       float64
Proposed Construction Type Description            object
Site Permit                                       object
Supervisor District                              float64
Neighborhoods - Analysis Boundaries               object
Zipcode                                          float64
Record ID                                        float64
Latitude                                          object
Longitude                                         object
dtype: object

In [130]:
df['Zipcode'] = df['Zipcode'].fillna('UNKNOWN')

In [131]:
df['Neighborhoods - Analysis Boundaries'] = df['Neighborhoods - Analysis Boundaries'].fillna('UNKNOWN')

In [132]:
df['Supervisor District'] = df['Supervisor District'].fillna(df['Supervisor District'].mean().round())

In [133]:
df

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Street Suffix,Description,...,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Record ID,Latitude,Longitude
0,201505000000.0,4,sign - erect,2015-05-06,326,23,140,Ellis,St,"ground fl facade: to erect illuminated, electr...",...,constr type 3,NaN,NaN,Y,3.0,Tenderloin,94102.0,1.380610e+12,37.785719256680785,-122.40852313194863
1,201604000000.0,4,sign - erect,2016-04-19,306,7,440,Geary,St,remove (e) awning and associated signs.,...,constr type 3,NaN,NaN,Y,3.0,Tenderloin,94102.0,1.420160e+12,37.78733980600732,-122.41063199757738
2,201605000000.0,3,additions alterations or repairs,2016-05-27,595,203,1647,Pacific,Av,installation of separating wall,...,constr type 1,1.0,constr type 1,Y,3.0,Russian Hill,94109.0,1.424860e+12,37.7946573324287,-122.42232562979227
3,201611000000.0,8,otc alterations permit,2016-11-07,156,11,1230,Pacific,Av,repair dryrot & stucco at front of bldg.,...,wood frame (5),5.0,wood frame (5),Y,3.0,Nob Hill,94109.0,1.443570e+12,37.79595867909168,-122.41557405519474
4,201611000000.0,6,demolitions,2016-11-28,342,1,950,Market,St,demolish retail/office/commercial 3-story buil...,...,constr type 3,NaN,NaN,Y,6.0,Tenderloin,94102.0,1.445480e+11,37.78315261897309,-122.40950883997789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15359,201306000000.0,8,otc alterations permit,2013-06-11,7104,018B,162,Farallones,St,"install finishing plumbing, finish electrical,...",...,wood frame (5),5.0,wood frame (5),Y,11.0,Oceanview/Merced/Ingleside,94112.0,1.307690e+12,37.7143177382725,-122.45793648914099
15360,201306000000.0,8,otc alterations permit,2013-06-11,3609,81,3549,20th,St,revision to 201208288466 to add a toilet in th...,...,wood frame (5),5.0,wood frame (5),Y,9.0,Mission,94110.0,1.307690e+12,37.7583635958755,-122.42012861020109
15361,201306000000.0,8,otc alterations permit,2013-06-11,3609,81,3551,20th,St,revision to 201208288466 to add a toilet in th...,...,wood frame (5),5.0,wood frame (5),Y,9.0,Mission,94110.0,1.307690e+12,37.7583635958755,-122.42012861020109
15362,201306000000.0,8,otc alterations permit,2013-06-11,4260,13,2334,25th,St,"interior renovation unit #2334, new kitchen fi...",...,wood frame (5),5.0,wood frame (5),Y,10.0,Potrero Hill,94107.0,1.307690e+12,37.752135529825054,-122.40206132582264
15363,M400947,8,otc alterations permit,2013-06-11,3701,53,66,08th,St,street space permit,...,NaN,NaN,NaN,Y,6.0,South of Market,94103.0,1.307690e+12,37.777338241377954,-122.41391079039403

In [134]:
df['Proposed Construction Type'] = df['Proposed Construction Type'].fillna(df['Proposed Construction Type'].mean()).round()

In [135]:
df

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Street Suffix,Description,...,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Record ID,Latitude,Longitude
0,201505000000.0,4,sign - erect,2015-05-06,326,23,140,Ellis,St,"ground fl facade: to erect illuminated, electr...",...,constr type 3,4.0,NaN,Y,3.0,Tenderloin,94102.0,1.380610e+12,37.785719256680785,-122.40852313194863
1,201604000000.0,4,sign - erect,2016-04-19,306,7,440,Geary,St,remove (e) awning and associated signs.,...,constr type 3,4.0,NaN,Y,3.0,Tenderloin,94102.0,1.420160e+12,37.78733980600732,-122.41063199757738
2,201605000000.0,3,additions alterations or repairs,2016-05-27,595,203,1647,Pacific,Av,installation of separating wall,...,constr type 1,1.0,constr type 1,Y,3.0,Russian Hill,94109.0,1.424860e+12,37.7946573324287,-122.42232562979227
3,201611000000.0,8,otc alterations permit,2016-11-07,156,11,1230,Pacific,Av,repair dryrot & stucco at front of bldg.,...,wood frame (5),5.0,wood frame (5),Y,3.0,Nob Hill,94109.0,1.443570e+12,37.79595867909168,-122.41557405519474
4,201611000000.0,6,demolitions,2016-11-28,342,1,950,Market,St,demolish retail/office/commercial 3-story buil...,...,constr type 3,4.0,NaN,Y,6.0,Tenderloin,94102.0,1.445480e+11,37.78315261897309,-122.40950883997789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15359,201306000000.0,8,otc alterations permit,2013-06-11,7104,018B,162,Farallones,St,"install finishing plumbing, finish electrical,...",...,wood frame (5),5.0,wood frame (5),Y,11.0,Oceanview/Merced/Ingleside,94112.0,1.307690e+12,37.7143177382725,-122.45793648914099
15360,201306000000.0,8,otc alterations permit,2013-06-11,3609,81,3549,20th,St,revision to 201208288466 to add a toilet in th...,...,wood frame (5),5.0,wood frame (5),Y,9.0,Mission,94110.0,1.307690e+12,37.7583635958755,-122.42012861020109
15361,201306000000.0,8,otc alterations permit,2013-06-11,3609,81,3551,20th,St,revision to 201208288466 to add a toilet in th...,...,wood frame (5),5.0,wood frame (5),Y,9.0,Mission,94110.0,1.307690e+12,37.7583635958755,-122.42012861020109
15362,201306000000.0,8,otc alterations permit,2013-06-11,4260,13,2334,25th,St,"interior renovation unit #2334, new kitchen fi...",...,wood frame (5),5.0,wood frame (5),Y,10.0,Potrero Hill,94107.0,1.307690e+12,37.752135529825054,-122.40206132582264
15363,M400947,8,otc alterations permit,2013-06-11,3701,53,66,08th,St,street space permit,...,NaN,4.0,NaN,Y,6.0,South of Market,94103.0,1.307690e+12,37.777338241377954,-122.41391079039403

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15364 entries, 0 to 15363
Data columns (total 39 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Permit Number                           15364 non-null  object
 1   Permit Type                             15364 non-null  int64
 2   Permit Type Definition                  15364 non-null  object
 3   Permit Creation Date                    15364 non-null  datetime64[ns]
 4   Block                                   15364 non-null  object
 5   Lot                                     15364 non-null  object
 6   Street Number                           15364 non-null  int64
 7   Street Name                             15364 non-null  object
 8   Street Suffix                           15364 non-null  object
 9   Description                             15339 non-null  object
 10  Current Status                          15364 non-null  object
 11  Current Status Date                     15364 non-null  datetime64[ns]
 12  Filed Date                              15364 non-null  datetime64[ns]
 13  Issued Date                             14729 non-null  datetime64[ns]
 14  Completed Date                          9129 non-null   datetime64[ns]
 15  First Construction Document Date        14725 non-null  datetime64[ns]
 16  Structural Notification                 15364 non-null  object
 17  Number of Existing Stories              15364 non-null  float64
 18  Number of Proposed Stories              15364 non-null  float64
 19  Fire Only Permit                        15364 non-null  object
 20  Permit Expiration Date                  11904 non-null  datetime64[ns]
 21  Estimated Cost                          15364 non-null  float64
 22  Revised Cost                            15364 non-null  float64
 23  Existing Use                            12266 non-null  object
 24  Existing Units                          11447 non-null  float64
 25  Proposed Use                            12031 non-null  object
 26  Proposed Units                          11346 non-null  float64
 27  Plansets                                12509 non-null  float64
 28  Existing Construction Type              12124 non-null  float64
 29  Existing Construction Type Description  12124 non-null  object
 30  Proposed Construction Type              15364 non-null  float64
 31  Proposed Construction Type Description  11947 non-null  object
 32  Site Permit                             15364 non-null  object
 33  Supervisor District                     15364 non-null  float64
 34  Neighborhoods - Analysis Boundaries     15364 non-null  object
 35  Zipcode                                 15364 non-null  object
 36  Record ID                               15364 non-null  float64
 37  Latitude                                15246 non-null  object
 38  Longitude                               15246 non-null  object
dtypes: datetime64[ns](7), float64(11), int64(2), object(19)
memory usage: 4.6+ MB

In [137]:
# df['Existing Construction Type'].()

SyntaxError: invalid syntax (2167408964.py, line 1)

In [ ]:
df['Existing Construction Type'] = df['Existing Construction Type'].fillna(df['Existing Construction Type'].mean()).round()

In [ ]:
# df['Revides'] = pd.cut(df['Revised Cost'], bins = [-np.inf, 1000, 10000, 100000, 1000000, 10000000, np.inf],
#                             labels=['Very Low', 'Low', 'Medium', 'High', 'Very High'])

In [142]:
df.drop(columns =['Permit Type', 'Permit Type Definition', 'Block', 'Lot', 'Street Number', 'Street Name', 'Street Suffix', 'Description', 'Current Status', 'Current Status Date', 'Filed Date', 'Issued Date', 'Completed Date', 'First Construction Document Date', 'Structural Notification', 'Number of Existing Stories', 'Number of Proposed Stories', 'Fire Only Permit', 'Estimated Cost', 'Existing Use', 'Existing Units', 'Proposed Use', 'Proposed Units', 'Plansets', 'Existing Construction Type Description', 'Proposed Construction Type', 'Proposed Construction Type Description', 'Site Permit', 'Supervisor District', 'Neighborhoods - Analysis Boundaries', 'Latitude', 'Longitude', 'Permit Expiration Date', 'Record ID', 'Permit Number', 'Existing Construction Type'], inplace = True)

In [140]:
df['Revised_Cost_Range'] = pd.cut(df['Revised Cost'], bins = [-np.inf, 1000, 10000, 100000, 1000000, 10000000, np.inf],
                            labels=['Very Low', 'Low', 'Medium', 'High', 'Very High', 'Extremely High'])

In [147]:
for x in df['Revised_Cost_Range'].unique():
    df[x] = np.where(df['Revised_Cost_Range']==x, 1, 0)

In [148]:
df.head(29)

,Permit Creation Date,Revised Cost,Zipcode,Revised_Cost_Range,Low,Very Low,High,Medium,Very High,Extremely High
0,2015-05-06,4000.0,94102.0,Low,1,0,0,0,0,0
1,2016-04-19,500.0,94102.0,Very Low,0,1,0,0,0,0
2,2016-05-27,111277.0,94109.0,High,0,0,1,0,0,0
3,2016-11-07,2000.0,94109.0,Low,1,0,0,0,0,0
4,2016-11-28,100000.0,94102.0,Medium,0,0,0,1,0,0
5,2017-06-14,4000.0,94107.0,Low,1,0,0,0,0,0
6,2017-06-30,12000.0,94122.0,Medium,0,0,0,1,0,0
7,2017-06-30,0.0,94124.0,Very Low,0,1,0,0,0,0
8,2017-07-05,1.0,94117.0,Very Low,0,1,0,0,0,0
9,2017-07-06,0.0,94117.0,Very Low,0,1,0,0,0,0
10,2017-07-06,1.0,94114.0,Very Low,0,1,0,0,0,0
11,2017-07-07,1.0,94102.0,Very Low,0,1,0,0,0,0
12,2017-07-10,1.0,94114.0,Very Low,0,1,0,0,0,0
13,2017-07-25,0.0,94131.0,Very Low,0,1,0,0,0,0
14,2017-07-26,1.0,94115.0,Very Low,0,1,0,0,0,0
15,2017-07-27,1.0,94108.0,Very Low,0,1,0,0,0,0
16,2017-07-27,1.0,94104.0,Very Low,0,1,0,0,0,0
17,2017-07-27,1.0,94114.0,Very Low,0,1,0,0,0,0
18,2017-07-28,0.0,94123.0,Very Low,0,1,0,0,0,0
19,2017-07-28,1.0,94114.0,Very Low,0,1,0,0,0,0
20,2017-07-31,1.0,94117.0,Very Low,0,1,0,0,0,0
21,2017-08-01,0.0,94110.0,Very Low,0,1,0,0,0,0
22,2017-08-01,111277.0,94133.0,High,0,0,1,0,0,0
23,2017-08-07,1.0,94123.0,Very Low,0,1,0,0,0,0
24,2017-08-08,64650.0,94123.0,Medium,0,0,0,1,0,0
25,2017-08-16,7000.0,94122.0,Low,1,0,0,0,0,0
26,2017-08-18,1.0,94121.0,Very Low,0,1,0,0,0,0
27,2017-08-21,1.0,94117.0,Very Low,0,1,0,0,0,0
28,2017-08-21,1.0,94122.0,Very Low,0,1,0,0,0,0

In [149]:
df.to_csv('Revised_cost.csv')